version: '3'

networks:
  elk:
    driver: bridge

services:
  elasticsearch:
    build:
      context:
        ./ELK/elasticsearch
      dockerfile:
        elasticsearch.Dockerfile
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    networks:
      - elk
  logstash:
    build:
      context:
        ./ELK/logstash
      dockerfile:
        logstash.Dockerfile
    container_name: logstash
    ports:
      - 5000:5000
      - 9600:9600
    depends_on:
      - elasticsearch
    networks:
      - elk
  kibana:
    build:
      context:
        ./ELK/kibana
      dockerfile:
        kibana.Dockerfile
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk
  mysql:
    image:
      mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticketing
      MYSQL_USER: cons
      MYSQL_PASSWORD: sa
    ports:
      - 3306:3306
  playground:
    image:
      mysql:8.0
    container_name: playground
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: playground
      MYSQL_USER: cons
      MYSQL_PASSWORD: sa
    ports:
      - 3307:3306
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeepr
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
