CREATE TABLE IF NOT EXISTS reserver (
                                        id BIGINT AUTO_INCREMENT PRIMARY KEY,
                                        point INTEGER
);

CREATE TABLE IF NOT EXISTS concert (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                       name VARCHAR(255),
                                        PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS concert_schedule (
                                                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                                concert_id BIGINT NOT NULL,
                                                start_at TIMESTAMP,
                                                capacity INTEGER,
                                                PRIMARY KEY (id),
    FOREIGN KEY (concert_id) REFERENCES concert(id)
    );


CREATE TABLE IF NOT EXISTS seat (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    seat_number INTEGER
);

CREATE TABLE IF NOT EXISTS concert_schedule_seat (
                                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                     concert_schedule_id BIGINT NOT NULL,
                                                     seat_id BIGINT NOT NULL,
                                                     price INTEGER NOT NULL,
                                                     CONSTRAINT UK_concert_schedule_seat UNIQUE (concert_schedule_id, seat_id),
    FOREIGN KEY (concert_schedule_id) REFERENCES concert_schedule(id),
    FOREIGN KEY (seat_id) REFERENCES seat(id)
    );

CREATE TABLE IF NOT EXISTS token (
                       id BIGINT AUTO_INCREMENT PRIMARY KEY,
                       user_id BIGINT NOT NULL,
                       status VARCHAR(255) NOT NULL,
                       expire_at TIMESTAMP NOT NULL,
                       created_at TIMESTAMP NOT NULL,
                       updated_at TIMESTAMP
);